name = "AncestralSequenceReconstruction"
uuid = "1d4f28ef-5432-422a-9dec-15ed9a8d60be"
authors = ["Pierre Barrat-Charlaix"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
